---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild-bazzite-dx
# description will be included in the image's metadata
description: Bazzite DX-based image with yeetmouse support and first-boot Flatpak installation

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: kargs
    kargs:
      - nvidia-drm.modeset=1

  - type: rpm-ostree
    repos:
      - https://abirkel.github.io/rpm-repo/stable.repo
    install:
      - kmod-yeetmouse
      - yeetmouse
      - konsole
    remove:
      # Remove Docker packages installed by bazzite-dx
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      # Remove Waydroid and related packages
      - waydroid
      - waydroid-selinux
      - cage
      - wlr-randr
      # Remove other unwanted packages
      - btop
      - Sunshine
      - ramalama
      - restic
      - zsh
      - android-tools
      - sysprof
      - ptyxis

  # Install flatpaks on first boot via BlueBuild module
  # Note: Runtimes are not supported by this module, only apps
  - type: default-flatpaks
    configurations:
      - scope: user
        notify: false
        install:
          # KDE Applications
          - org.kde.krita
          - org.kde.okular
          - org.kde.gwenview
          - org.kde.kcalc
          # KDE Themes
          - org.gtk.Gtk3theme.Breeze
          # Gaming & Wine
          - com.github.Matoking.protontricks
          - com.usebottles.bottles
          - io.github.fastrizwaan.WineZGUI
          - net.davidotek.pupgui2
          - com.vysp3r.ProtonPlus
          - io.github.Faugus.faugus-launcher
          # System Utilities
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - it.mijorus.gearlever
          - org.freedesktop.Piper
          # Development & Containers
          - io.podman_desktop.PodmanDesktop
          - io.github.DenysMb.Kontainer
          # Media & Creative
          - com.github.PintaProject.Pinta
          - io.github.mpc_qt.mpc-qt
          # Communication
          - dev.vencord.Vesktop
          # Other
          - de.leopoldluley.Clapgrep
          - org.fedoraproject.MediaWriter
          - org.localsend.localsend_app
          - org.mozilla.firefox

  # Copy hook to disable flatpak auto-install after first run
  - type: files
    files:
      - source: system
        destination: /

  # Fetch Aurora blocklist dynamically
  - type: script
    scripts:
      - fetch-aurora-blocklist.sh

  # Install Microsoft TrueType Core Fonts
  - type: script
    scripts:
      - install-msttcorefonts.sh

  # Clean up Docker configurations from bazzite-dx base
  - type: script
    scripts:
      - cleanup-docker.sh

  - type: signing  # Sets up policy & signing files for signed images
